### ISSUE TITLE
Grid images

### ISSUE THREAD

**Issue by pachonk** [Mingosio/celebrity-picture-rater#21]
@d4rkd0s said he used
```css
.timg {
    height: 150px;
    width: auto;
    margin: 12px;
    transition-duration: 120ms;
    user-select: none;
    border-radius: 8px;
    border: 1px solid transparent;
}
```
previously
